### ISSUE TITLE
ServiceControl.Contracts is not signed

### ISSUE THREAD

**Issue by kbaley** [Particular/ServiceControl.Contracts#26]
The `NServiceBus.snk` file is included in the repo but the package is not being signed. This might be by design but if so, it's not documented.

**Comment by rickdsw** [comment]
Is there an update to this issue?

**Comment by kbaley** [comment]
@rickdsw We'll include this in an upcoming maintenance release. I'm not sure yet when that will be but we go through them for all our products pretty regularly.

**Comment by rickdsw** [comment]
@kbaley Hey Kyle thanks for the update. Do you already know when the upcoming maintenance release will be?

**Comment by adamralph** [comment]
@rickdsw we don't have the next maintenance release scheduled yet, but we'll update this issue when we do.

**Comment by rickdsw** [comment]
@adamralph Thank you for your answer, I will wait for the update of this issue.

**Comment by rickdsw** [comment]
Hello, it has been several months since this issue has been opened. Do you have any indication on when this issue is going to be resolved?

**Comment by HEskandari** [comment]
@rickdsw I have done a bit of investigation to make sure this doesn't break existing contract/communication with the ServiceControl and that seem to be a non-issue. I have created a PR to address it. Please stay tuned.

**Comment by HEskandari** [comment]
Closed via #41

**Comment by HEskandari** [comment]
@rickdsw apologies for the delay, but this is now released.
